### ISSUE TITLE
support nodejs v18

### ISSUE THREAD

**Issue by jasonHzq** [srcbookdev/srcbook#189]
running command as below:

```
srcbook start
```

cli throw error messages:

```sh
~/.nvm/versions/node/v18.17.0/lib/node_modules/srcbook/node_modules/@srcbook/shared/dist/src/utils.js:3
    const bytes = crypto.getRandomValues(new Uint8Array(byteSize));
                  ^

ReferenceError: crypto is not defined
    at randomid (~/.nvm/versions/node/v18.17.0/lib/node_modules/srcbook/node_modules/@srcbook/shared/dist/src/utils.js:3:19)
    at ~/.nvm/versions/node/v18.17.0/lib/node_modules/srcbook/lib/db/schema.mjs:13:66
```

I see your document nodejs version requirements is v20+.   can you support nodejs v18.

**Comment by nichochar** [comment]
Yeah, we're aware of this. For now, can you use node 20+? We recommend using https://github.com/nvm-sh/nvm
