### ISSUE TITLE
Error parsing XML: Error: CDATA is not closed.

### ISSUE THREAD

**Issue by a1ooha** [srcbookdev/srcbook#465]
```bash
Error parsing XML: Error: CDATA is not closed.
    at findClosingIndex (/Users/aloha/Code/github.com/srcbookdev/srcbook/node_modules/.pnpm/fast-xml-parser@4.5.0/node_modules/fast-xml-parser/src/xmlparser/OrderedObjParser.js:503:11)
    at OrderedObjParser.parseXml (/Users/aloha/Code/github.com/srcbookdev/srcbook/node_modules/.pnpm/fast-xml-parser@4.5.0/node_modules/fast-xml-parser/src/xmlparser/OrderedObjParser.js:270:28)
    at XMLParser.parse (/Users/aloha/Code/github.com/srcbookdev/srcbook/node_modules/.pnpm/fast-xml-parser@4.5.0/node_modules/fast-xml-parser/src/xmlparser/XMLParser.js:35:48)
    at Module.parsePlan (/Users/aloha/Code/github.com/srcbookdev/srcbook/packages/api/ai/plan-parser.mts:108:27)
    at Module.createAppWithAi (/Users/aloha/Code/github.com/srcbookdev/srcbook/packages/api/apps/app.mts:57:22)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at /Users/aloha/Code/github.com/srcbookdev/srcbook/packages/api/server/http.mts:449:19
Error: Failed to parse XML response
    at Module.parsePlan (/Users/aloha/Code/github.com/srcbookdev/srcbook/packages/api/ai/plan-parser.mts:160:11)
    at Module.createAppWithAi (/Users/aloha/Code/github.com/srcbookdev/srcbook/packages/api/apps/app.mts:57:22)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at /Users/aloha/Code/github.com/srcbookdev/srcbook/packages/api/server/http.mts:449:19
```

**Comment by aakash-a-dev** [comment]
Can you share how you reproduce this error

**Comment by a1ooha** [comment]
Just use the placeholder content to create app.

![image](https://github.com/user-attachments/assets/c90735bb-a79f-4ce3-8806-f949100d7d66)

- Node 22.7.0
- Pnpm 9.12.1
- macOS 15.1.1

**Comment by nichochar** [comment]
This is a transient error and shouldn't happen to often. There's no easy fix. Just try asking the AI again.

Make sure you're using claude 3.5 sonnet from anthropic. It's the model which has the least issues.
